Various fixes to make it easier to run in diverse environments
Removed all the lsb helper utils from the sysv init script
Added a better error message for template missing.
Added the ability to skip the definition of the monasca_api_url
Made check frequency configurable and added an option to monasca setup
Also set the forwarder flush interval to be calculated based on check
frequency.
Modified monasca-setup so it can work with non-standard paths.

Change-Id: If8916e17bf42ffb804fa6c79166149a9fd33c553

diff --git a/packaging/monasca-agent.init.template b/packaging/monasca-agent.init.template
--- a/packaging/monasca-agent.init.template
+++ b/packaging/monasca-agent.init.template
@@ -10,20 +10,19 @@
 # Default-Stop: 0 1 6
 ### END INIT INFO
 
-. /lib/lsb/init-functions
 PATH=$PATH:/usr/local/bin # supervisord might live here
-PATH=$PATH:/sbin # add the location of start-stop-daemon on Debian
+PATH=$PATH:/sbin
 
-AGENTPATH="/usr/local/bin/monasca-collector"
-AGENTCONF="/etc/monasca/agent/agent.conf"
-MONASCASTATSDPATH="/usr/local/bin/monasca-statsd"
+AGENTPATH="{prefix}/bin/monasca-collector"
+AGENTCONF="{config_dir}/agent.conf"
+MONASCASTATSDPATH="{prefix}/bin/monasca-statsd"
 AGENTUSER="monasca-agent"
-FORWARDERPATH="/usr/local/bin/monasca-forwarder"
+FORWARDERPATH="{prefix}/bin/monasca-forwarder"
 NAME="monasca-agent"
 DESC="Monasca Monitoring Agent"
 AGENT_PID_PATH="/var/tmp/monasca-agent.pid"
 SUPERVISOR_PIDFILE="/var/tmp/monasca-agent-supervisord.pid"
-SUPERVISOR_FILE="/etc/monasca/agent/supervisor.conf"
+SUPERVISOR_FILE="{config_dir}/supervisor.conf"
 SUPERVISOR_SOCK="/var/tmp/monasca-agent-supervisor.sock"
 SUPERVISORD=$(which supervisord)
 
@@ -35,7 +34,7 @@ if [ ! -x $AGENTPATH ]; then
     exit 0
 fi
 
-check_status() {
+check_status() {{
     # If the socket exists, we can use supervisorctl
     if [ -e $SUPERVISOR_SOCK ]; then
         # If we're using supervisor, check the number of processes
@@ -63,7 +62,7 @@ check_status() {
         echo "$DESC (supervisor) is not running"
         return 1
     fi
-}
+}}
 
 # Action to take
 case "$1" in
@@ -81,23 +80,22 @@ case "$1" in
 
         su $AGENTUSER -c "$AGENTPATH configcheck" > /dev/null
         if [ $? -ne 0 ]; then
-            log_daemon_msg "Invalid check configuration. Please run sudo /etc/init.d/monasca-agent configtest for more details."
-            log_daemon_msg "Resuming starting process."
+            echo "Invalid check configuration. Please run sudo /etc/init.d/monasca-agent configtest for more details."
+            echo "Resuming starting process."
         fi
 
-       
-        log_daemon_msg "Starting $DESC (using supervisord)" "$NAME"
-        start-stop-daemon --start --quiet --oknodo --exec $SUPERVISORD -- -c $SUPERVISOR_FILE -u $AGENTUSER --pidfile $SUPERVISOR_PIDFILE
+
+        echo "Starting $DESC (using supervisord)" "$NAME"
+        $SUPERVISORD -c $SUPERVISOR_FILE -u $AGENTUSER --pidfile $SUPERVISOR_PIDFILE
         if [ $? -ne 0 ]; then
-            log_end_msg 1
+            exit $?
         fi
-   
+
         # check if the agent is running once per second for 10 seconds
         retries=10
         while [ $retries -gt 1 ]; do
           if check_status > /dev/null; then
               # We've started up successfully. Exit cleanly
-              log_end_msg 0
               exit 0
           else
               retries=$(($retries - 1))
@@ -105,17 +103,21 @@ case "$1" in
           fi
         done
         # After 10 tries the agent didn't start. Report an error
-        log_end_msg 1
+        exit 1
         check_status # report what went wrong
         $0 stop
         exit 1
         ;;
     stop)
-       
-        log_daemon_msg "Stopping $DESC (stopping supervisord)" "$NAME"
-        start-stop-daemon --stop --retry 30 --quiet --oknodo --pidfile $SUPERVISOR_PIDFILE
-   
-        log_end_msg $?
+
+        echo "Stopping $DESC (stopping supervisord)" "$NAME"
+        if [ -e $SUPERVISOR_PIDFILE ]; then
+          kill `cat $SUPERVISOR_PIDFILE`
+        else
+          echo "Pid file $SUPERVISOR_PIDFILE not found, nothing to stop"
+        fi
+
+        exit $?
 
         ;;
 
@@ -158,8 +160,7 @@ case "$1" in
         ;;
 
     *)
-        N=/etc/init.d/$NAME
-        echo "Usage: $N {start|stop|restart|info|status|configcheck|configtest|jmx}"
+        echo "Usage: /etc/init.d/$NAME {{start|stop|restart|info|status|configcheck|configtest|jmx}}"
         exit 1
         ;;
 esac
